sudo: required
dist: trusty

language: node_js
node_js:
  - "4.1"
python:
  - "3.4"

cache:
  pip: true
  directories:
    - node_modules

before_install:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U pip setuptools virtualenvwrapper

  - npm install -g bower
  - bower install
  - sudo pip3 install -r requirements.txt

after_script:
  - coala
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
